[versions]
jetbrainscompose = "1.6.1"
kotlin = "1.9.23"

[libraries]

[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "jetbrainscompose" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }